openapi: 3.0.0
servers: []
info:
  version: "0.0.2"
  title: Airline data definitions
  description: Object definitions for the airline part of the WT platform.
paths: {}
components:
  schemas:
    AirlineOnChain:
      title: WT-Index airline record
      description: Airline record in WT-Index smart contract
      type: object
      required:
      - address
      - manager
      - dataUri
      - created
      properties:
        address:
          description: Ethereum address of the airline
          $ref: 'https://raw.githubusercontent.com/windingtree/wiki/2c6312c06b15a2c12fe764ce10bdb6c4a0f78843/shared-resources.yaml#/components/schemas/EthereumAddressType'
        manager:
          description: Ethereum address of the manager wallet
          $ref: 'https://raw.githubusercontent.com/windingtree/wiki/2c6312c06b15a2c12fe764ce10bdb6c4a0f78843/shared-resources.yaml#/components/schemas/EthereumAddressType'
        dataUri:
          description: URI of the Airline data index (pointing off-chain)
          $ref: 'https://raw.githubusercontent.com/windingtree/wiki/2c6312c06b15a2c12fe764ce10bdb6c4a0f78843/shared-resources.yaml#/components/schemas/UriType'
        created:
          description: Number of a block when the airline was created
          type: integer

    # Off chain data formats  
    AirlineDataIndex:
      title: Airline data index
      description: Landing index for airline resources. Link to this document is stored in WT-Index smart contract airline record.
      type: object
      required:
      - dataFormatVersion
      - descriptionUri
      properties:
        dataFormatVersion:
          description: Version number indicating the data format specification version.
          type: string
          format: semver
          maxLength: 20
        descriptionUri:
          description: URI pointing to the AirlineDescription data resource
          $ref: 'https://raw.githubusercontent.com/windingtree/wiki/2c6312c06b15a2c12fe764ce10bdb6c4a0f78843/shared-resources.yaml#/components/schemas/UriType'
        flightsUri:
          $ref: 'https://raw.githubusercontent.com/windingtree/wiki/2c6312c06b15a2c12fe764ce10bdb6c4a0f78843/shared-resources.yaml#/components/schemas/UriType'
          description: URI pointing to Flights data resource
        notificationsUri:
          $ref: '#/components/schemas/UriType'
          description: URI pointing to an instance of the WT Notification service.
        bookingUri:
          $ref: 'https://raw.githubusercontent.com/windingtree/wiki/2c6312c06b15a2c12fe764ce10bdb6c4a0f78843/shared-resources.yaml#/components/schemas/UriType'
          description: URI pointing to an instance of the WT Booking service.
    AirlineDescription:
      title: Airline description.
      description: Basic properties of an airline.
      type: object
      required:
      - name
      - code
      - contacts
      - updatedAt
      - defaultCancellationAmount
      properties:
        name:
          description: Name of the airline to display to users
          $ref: 'https://raw.githubusercontent.com/windingtree/wiki/2c6312c06b15a2c12fe764ce10bdb6c4a0f78843/shared-resources.yaml#/components/schemas/NameType'
        code:
          $ref: '#/components/schemas/AirlineCodeType'
        contacts:
          type: object
          description: A set of contacts.
          required:
          - general
          properties:
            general:
              description: Primary contact
              $ref: 'https://raw.githubusercontent.com/windingtree/wiki/2c6312c06b15a2c12fe764ce10bdb6c4a0f78843/shared-resources.yaml#/components/schemas/Contact'
        updatedAt:
          type: string
          description: Date-time when the data was last changed. Used by consumers to handle incremental updates and caching.
          format: date-time
        defaultCancellationAmount:
          type: number
          format: float
          description: Cost of cancellation in percents of the final price, 100 means non refundable. This is a default amount of how much money will the airline keep if no other cancallation policy is applicable.
          example: 25
        cancellationPolicies:
          description: A list of policies under which it is possible to cancel a reservation.
          type: array
          items:
            $ref: '#/components/schemas/CancellationPolicy'
    Flights:
      type: object
      description: A set of scheduled flights.
      required:
        - updatedAt
        - flights
      properties:
        flights:
          type: array
          description: Array of Flights
          items:
            $ref: '#/components/schemas/Flight'
        updatedAt:
          description: Time of the last update of services information.
          type: string
          format: date-time
    Flight:
      type: object
      description: A single airline service.
      required:
        - id
        - origin
        - destination
        - segments
        - flightInstancesUri
      properties:
        id:
          description: A flight ID.
          type: string
          maxLength: 255
          example: 'OK0965'
        origin:
          description: IATA code of the origin airport.
          $ref: '#/components/schemas/AirportCodeType'
        destination:
          description: IATA code of the destination airport.
          $ref: '#/components/schemas/AirportCodeType'
        equipmentType:
          $ref: '#/components/schemas/EquipmentType'
        operatingAirline:
          $ref: '#/components/schemas/AirlineCodeType'
        segments:
          type: array
          minItems: 1
          items:
            type: object
            required:
              - id
              - departureAirport
              - arrivalAirport
            properties:
              id:
                title: ID of the flight segment (must be unique for the given flight number).
                type: string
              departureAirport:
                description: IATA code of the departure airport.
                $ref: '#/components/schemas/AirportCodeType'
              arrivalAirport:
                description: IATA code of the arrival airport.
                $ref: '#/components/schemas/AirportCodeType'
        flightInstancesUri:
          $ref: 'https://raw.githubusercontent.com/windingtree/wiki/2c6312c06b15a2c12fe764ce10bdb6c4a0f78843/shared-resources.yaml#/components/schemas/UriType'
          description: URI pointing to the FlightInstances resource.
    FlightInstances:
      description: Array of flight instances for a specific flight number.
      type: array
      items:
        $ref: '#/components/schemas/FlightInstance'
    FlightInstance:
      type: object
      description: Data for a specific flight.
      required:
        - id
        - departureDateTime
        - segments
        - updatedAt
      properties:
        id:
          description: A reference flight ID to be used during booking.
          type: string
          maxLength: 255
          example: 'IeKeix6G'
        departureDateTime:
          description: Date and time of departure from the first segment
          type: string
          format: date-time
        bookingClassess:
          description: |
            Array of price and availability information for
            various booking classes of the flight. In the
            future, this information might become more granular
            (per segment instead of per flight).
          type: array
          items:
            type: object
            required:
              - id
              - name
              - fare
              - availabilityCount
            properties:
              id:
                description: |
                    ID of the booking class to be referenced in
                    booking requests. Should be unique among all
                    booking classes of the flight.
                type: string
                maxLength: 255
                example: 'economy'
              name:
                description: A human-readable name of the booking class.
                type: string
                maxLength: 255
                example: 'Economy'
              fare:
                description: Fare price, potentially expressed in multiple currencies.
                type: array
                items:
                  $ref: '#/components/schemas/Fare'
              availabilityCount:
                type: integer
                format: int32
        segments:
          description: |
            An object whose keys are segment IDs (they should match the segment IDs in the Flight data).
            It specifies information for individual flight segments for the given flight instance.
          type: object
          additionalProperties:
            type: object
            required:
              - departureDateTime
              - arrivalDateTime
              - bookingClasses
            properties:
              departureDateTime:
                description: Time of the departure.
                type: string
                format: date-time
              arrivalDateTime:
                description: Time of the arrival.
                type: string
                format: date-time
        updatedAt:
          description: Time of the last update of flight information.
          type: string
          format: date-time
    Fare:
      type: object
      required:
        - amount
        - currency
      properties:
        amount:
          description: Fare price for the flight segment.
          type: number
          format: float
        currency:
          description: Fare price currency.
          $ref: 'https://raw.githubusercontent.com/windingtree/wiki/2c6312c06b15a2c12fe764ce10bdb6c4a0f78843/shared-resources.yaml#/components/schemas/CurrencyType'
    CancellationPolicy:
      title: Cancellation policy
      type: object
      description: What is the penalty when a passanger wants to cancel a reservation.
      required:
      - amount
      properties:
        from:
          description: After which date does this cancellation policy apply (including). If not present, this policy applies since the beginning of time. This is related to arrival and departure dates, not the date of the booking.
          type: string
          format: date-time
          example: "2018-01-30 00:00:00"
        to:
          description: Before which date does this cancellation policy apply (including). If not present, this policy applies until the end of the universe. This is related to arrival and departure dates, not the date of the booking.
          type: string
          format: date-time
          example: "2018-02-20 12:00:00"
        deadline:
          type: integer
          description: How many days before arrival does this first apply. If not present, this policy applies any time.
          example: 30
        amount:
          type: number
          format: float
          description: Cost of cancellation in percents of the final price, 100 means non refundable. This means how much money will the hotel keep.
          example: 25
  # elementary schemas
    AirlineCodeType:
      title: Airline Code.
      description: IATA 2-Letter Airline code.
      type: string
      minLength: 2
      maxLength: 2
    AirportCodeType:
      title: Airport Code.
      description: IATA 3-Letter Airport code.
      type: string
      minLength: 3
      maxLength: 3
    EquipmentType:
      title: Airline equipment type (aircraft).
      type: string
      maxLength: 255
